apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: cloudprojekt
  name: cloudprojekt
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudprojekt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudprojekt    
    spec:
      containers:
      - image: cntmodul/cloudprojekt
        imagePullPolicy: IfNotPresent
        name: cloudprojekt
        env:
        - name: DATABASE_HOST
          value: localhost
        - name: DATABASE_USER 
          value: dbuser         
        - name: DATABASE_NAME 
          value: phplogin
        - name: DATABASE_PASS 
          valueFrom:
           secretKeyRef:
            name: database-pass
            key: password       
